export const GET_TODAY_LIST = 'GET_TODAY_LIST';
export const GET_NOPLANB_LIST = 'GET_NOPLANB_LIST';
export const GET_UPCOMING_LIST = 'GET_UPCOMING_LIST';
export const GET_PROJECTS = 'GET_PROJECTS';
export const CREATE_PROJECT = 'CREATE_PROJECT';
export const TOGGLE_PROJECT_FORM = 'TOGGLE_PROJECT_FORM';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
